<?xml version="1.0" encoding="UTF-8"?>
<robot name="armed3w" xmlns:xacro="http://ros.org/wiki/xacro">
  <xacro:include filename="$(find robot_utokyo)/urdf/armed3w.gazebo.xacro"/>

  <xacro:property name="body_height" value="0.4" />
  <xacro:property name="wheel_radius" value="0.05" />
  <xacro:property name="arm_length" value="0.6" />
  <xacro:property name="pi" value="3.1415926" />
  <xacro:property name="sensor_size" value=".1" />

  <link name="base_footprint"/>

  <!-- Robot Body -->
  <joint name="base_link_joint" type="fixed">
    <parent link="base_footprint"/>
    <child link="body"/>
    <origin xyz="-4 5 0"/>
  </joint>

  <link name='body'>
    <inertial>
      <mass value="1"/>
      <!-- #cylinder Izz = 1/2 * M * r^2
      #cylinder Iyy = Ixx = 1/12 * M * l^2 -->
      <inertia ixx=".0675"  ixy="0"  ixz="0" iyy=".0675" iyz="0" izz=".045"/>
    </inertial>
    <collision>
      <origin xyz="0 0 0" rpy="0 0 0"/>
      <geometry>
        <cylinder radius=".3" length="${body_height}"/>
      </geometry>
    </collision>
    <visual>
      <origin xyz="0 0 0" rpy="0 0 0"/>
      <geometry>
        <cylinder radius=".3" length="${body_height}"/>
      </geometry>
    </visual>
  </link>

  <joint name="body_wheelFront" type="fixed">
    <parent link="body"/>
    <child link="wheelFront"/>
    <origin xyz="0 .2 ${- body_height / 2 - wheel_radius / 2}" rpy="0 0 0"/>
  </joint>

  <link name='wheelFront'>
    <inertial>
      <mass value=".2"/>
      <!-- # sphere: I = 2/5 * M * a^2 -->
      <inertia ixx=".0002"  ixy="0"  ixz="0" iyy=".0002" iyz="0" izz=".0002"/>
    </inertial>
    <collision>
      <origin xyz="0 0 0" rpy="0 0 0"/>
      <geometry>
        <sphere radius="${wheel_radius}"/>
      </geometry>
    </collision>
    <visual>
      <origin xyz="0 0 0" rpy="0 0 0"/>
      <geometry>
        <sphere radius="${wheel_radius}"/>
      </geometry>
    </visual>
  </link>

  <joint name="body_wheelRight" type="continuous">
    <parent link="body"/>
    <child link="wheelRight"/>
    <origin xyz="0.1732 -.1 ${- body_height / 2 - wheel_radius / 2}" rpy="0 0 0"/>
    <axis xyz="1 0 0"/>
  </joint>

  <link name='wheelRight'>
    <inertial>
      <mass value=".2"/>
      <!-- # sphere: I = 2/5 * M * r^2 -->
      <inertia ixx=".0002"  ixy="0.0"  ixz="0.0" iyy=".0002" iyz="0.0" izz=".0002"/>
    </inertial>
    <collision>
      <origin xyz="0 0 0" rpy="0 0 0"/>
      <geometry>
        <sphere radius="${wheel_radius}"/>
      </geometry>
    </collision>
    <visual>
      <origin xyz="0 0 0" rpy="0 0 0"/>
      <geometry>
        <sphere radius="${wheel_radius}"/>
      </geometry>
    </visual>
  </link>

  <joint name="body_wheelLeft" type="continuous">
    <parent link="body"/>
    <child link="wheelLeft"/>
    <origin xyz="-0.1732 -.1 ${- body_height / 2 - wheel_radius / 2}" rpy="0 0 0"/>
    <axis xyz="1 0 0"/>
  </joint>

  <link name='wheelLeft'>
    <inertial>
      <mass value=".2"/>
      <!-- # sphere: I = 2/5 * M * r^2 -->
      <inertia ixx=".0002"  ixy="0.0"  ixz="0.0" iyy=".0002" iyz="0.0" izz=".0002"/>
    </inertial>
    <collision>
      <origin xyz="0 0 0" rpy="0 0 0"/>
      <geometry>
        <sphere radius="${wheel_radius}"/>
      </geometry>
    </collision>
    <visual>
      <origin xyz="0 0 0" rpy="0 0 0"/>
      <geometry>
        <sphere radius="${wheel_radius}"/>
      </geometry>
    </visual>
  </link>

  <joint name="body_armRight" type="continuous">
    <parent link="body"/>
    <child link="armRight"/>
    <origin xyz=".3 0 .2" rpy="${- pi / 2} 0 0"/>
    <axis xyz="1 0 0"/>
  </joint>

  <link name='armRight'>
    <inertial>
      <mass value=".1"/>
      <!-- #cylinder Izz = 1/2 * M * r^2 -->
      <!-- #cylinder Iyy = Ixx = 1/12 * M * l^2 -->
      <inertia ixx=".003"  ixy="0"  ixz="0" iyy=".003" iyz="0" izz=".000045"/>
    </inertial>
    <collision>
      <origin xyz="0 0 -.3" rpy="0 0 0"/>
      <geometry>
        <cylinder radius=".03" length="${arm_length}"/>
      </geometry>
    </collision>
    <visual>
      <origin xyz="0 0 -.3" rpy="0 0 0"/>
      <geometry>
        <cylinder radius=".03" length="${arm_length}"/>
      </geometry>
    </visual>
  </link>

  <joint name="body_armLeft" type="continuous">
    <parent link="body"/>
    <child link="armLeft"/>
    <origin xyz="-.3 0 .2" rpy="${- pi / 2} 0 0"/>
    <axis xyz="1 0 0"/>
  </joint>

  <link name='armLeft'>
      <inertial>
        <mass value=".1"/>
      <!-- #cylinder Izz = 1/2 * M * r^2
      #cylinder Iyy = Ixx = 1/12 * M * l^2 -->
      <inertia ixx=".003"  ixy="0"  ixz="0" iyy=".003" iyz="0" izz=".000045"/>
      </inertial>
      <collision>
        <origin xyz="0 0 -.3" rpy="0 0 0"/>
        <geometry>
          <cylinder radius=".03" length="${arm_length}"/>
        </geometry>
      </collision>
      <visual>
        <origin xyz="0 0 -.3" rpy="0 0 0"/>
        <geometry>
          <cylinder radius=".03" length="${arm_length}"/>
        </geometry>
      </visual>
    </link>

  <!-- controller start-->
  <transmission name="body_wheelRight_trans">
    <type>transmission_interface/SimpleTransmission</type>
    <joint name="body_wheelRight">
      <hardwareInterface>hardware_interface/VelocityJointInterface</hardwareInterface>
    </joint>
    <actuator name="body_wheelRight_motor">
      <hardwareInterface>VelocityJointInterface</hardwareInterface>
      <mechanicalReduction>30</mechanicalReduction>
    </actuator>
  </transmission>

  <transmission name="body_wheelLeft_trans">
    <type>transmission_interface/SimpleTransmission</type>
    <joint name="body_wheelLeft">
      <hardwareInterface>hardware_interface/VelocityJointInterface</hardwareInterface>
    </joint>
    <actuator name="body_wheelLeft_motor">
      <hardwareInterface>VelocityJointInterface</hardwareInterface>
      <mechanicalReduction>30</mechanicalReduction>
    </actuator>
  </transmission>

  <transmission name="body_armRight_trans">
    <type>transmission_interface/SimpleTransmission</type>
    <joint name="body_armRight">
      <hardwareInterface>hardware_interface/VelocityJointInterface</hardwareInterface>
    </joint>
    <actuator name="body_armRight_motor">
      <hardwareInterface>VelocityJointInterface</hardwareInterface>
      <mechanicalReduction>30</mechanicalReduction>
    </actuator>
  </transmission>

  <transmission name="body_armLeft_trans">
    <type>transmission_interface/SimpleTransmission</type>
    <joint name="body_armLeft">
      <hardwareInterface>hardware_interface/VelocityJointInterface</hardwareInterface>
    </joint>
    <actuator name="body_armLeft_motor">
      <hardwareInterface>VelocityJointInterface</hardwareInterface>
      <mechanicalReduction>30</mechanicalReduction>
    </actuator>
  </transmission>
  <!-- controller end-->

  <joint name="camera_joint" type="fixed">
    <origin xyz="0 -.4 0" rpy="0 0 0"/>
    <parent link="body"/>
    <child link="camera"/>
  </joint>

  <link name="camera">
    <collision>
      <origin xyz="0 0 0" rpy="0 0 0"/>
      <geometry>
        <box size="${sensor_size} ${sensor_size} ${sensor_size}"/>
      </geometry>
    </collision>

    <visual>
      <origin xyz="0 0 0" rpy="0 0 0"/>
      <geometry>
        <box size="${sensor_size} ${sensor_size} ${sensor_size}"/>
      </geometry>
      <material name="green"/>
    </visual>

    <inertial>
      <mass value=".01" />
      <origin xyz="0 0 0" rpy="0 0 0"/>
      <box_inertia m=".01" x=".1" y=".1" z=".1" />
      <inertia ixx="1e-6" ixy="0" ixz="0" iyy="1e-6" iyz="0" izz="1e-6" />
    </inertial>
  </link>


  <joint name="hokuyo_joint" type="fixed">
    <origin xyz="0 0 ${body_height / 2 + sensor_size / 2}" rpy="0 0 -1.570796"/>
    <parent link="body"/>
    <child link="hokuyo"/>
  </joint>

  <!-- Hokuyo Laser -->
  <link name="hokuyo">
    <collision>
      <origin xyz="0 0 0" rpy="0 0 0"/>
      <geometry>
        <box size="${sensor_size} ${sensor_size} ${sensor_size}"/>
      </geometry>
    </collision>

    <visual>
      <origin xyz="0 0 0" rpy="0 0 0"/>
      <geometry>
        <box size="${sensor_size} ${sensor_size} ${sensor_size}"/>
      </geometry>
    </visual>

    <inertial>
      <mass value="1e-5" />
      <origin xyz="0 0 0" rpy="0 0 0"/>
      <inertia ixx="1e-6" ixy="0" ixz="0" iyy="1e-6" iyz="0" izz="1e-6" />
    </inertial>
  </link>

</robot>
